condense_wildcard_suffixes = true
use_field_init_shorthand = true
format_strings =  true
force_multiline_blocks = true
hard_tabs = true
match_block_trailing_comma = true
max_width = 80
merge_imports = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
wrap_comments = true
